Revert "Bump gensim from 3.8.3 to 4.3.1 in /RIMA-Backend"
This reverts commit 4326c07431499046fd4ea447d827df7bd3eb6e65.

ModuleNotFoundError: No module named 'gensim.models.wrappers'

see: https://stackoverflow.com/questions/66884353/modulenotfounderror-no-module-named-gensim-models-wrappers